"""
N4 — Generated File Detector

Fast 3-stage check: filename → pattern → content header (first 500 bytes).
Skips generated files before any processing begins.

Estimated savings: 20–30% of files that would otherwise waste LLM calls.
"""
from __future__ import annotations

import re
from pathlib import Path

# ── Exact filename blocklist ───────────────────────────────────────────────────
SKIP_NAMES: frozenset[str] = frozenset({
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "Cargo.lock", "poetry.lock", "Pipfile.lock",
    "composer.lock", "Gemfile.lock", "bun.lockb",
    ".DS_Store", "Thumbs.db", "desktop.ini",
    "MANIFEST.in",
})

# ── Filename pattern blocklist ─────────────────────────────────────────────────
SKIP_PATTERNS: list[re.Pattern] = [
    re.compile(r"\.min\.(js|css)$", re.I),
    re.compile(r"\.bundle\.(js|css)$", re.I),
    re.compile(r"[-.]generated\.\w+$", re.I),
    re.compile(r"\.pb\.go$"),                   # protobuf Go
    re.compile(r"_pb2(_grpc)?\.py$"),           # protobuf Python
    re.compile(r"\.g\.dart$"),                  # Flutter generated
    re.compile(r"\.freezed\.dart$"),            # Flutter freezed
    re.compile(r"\.gr\.dart$"),                 # auto_route
    re.compile(r"__generated__"),               # GraphQL codegen
    re.compile(r"\.snap$"),                     # Jest snapshots
    re.compile(r"schema\.generated\.\w+$", re.I),
    re.compile(r"migrations?/\d{4}", re.I),     # Django/Alembic migrations
    re.compile(r"\.d\.ts$"),                    # TypeScript declaration files
    re.compile(r"stubs?/.*\.py$", re.I),
]

# ── Content header signatures (bytes, checked in first 500 bytes) ──────────────
GENERATED_SIGNATURES: list[bytes] = [
    b"// Code generated by",
    b"// DO NOT EDIT",
    b"// This file was generated",
    b"// Auto-generated",
    b"// Generated by",
    b"/* eslint-disable */",
    b"# This file is auto-generated",
    b"# DO NOT EDIT",
    b"# Generated by",
    b"// GENERATED CODE - DO NOT MODIFY BY HAND",  # Flutter
    b"THIS FILE IS GENERATED",
    b"@generated",
    b"// autogenerated",
    b"# autogenerated",
    b"AUTOGENERATED FILE",
]


def is_generated(path: Path) -> bool:
    """
    Return True if this file is machine-generated and should be skipped.
    Performs three fast checks in increasing cost order:
      1. Exact filename match (O(1))
      2. Regex pattern match on filename (O(patterns))
      3. Read first 500 bytes for generation signature (1 syscall)
    """
    if path.name in SKIP_NAMES:
        return True

    name_lower = path.name.lower()
    str_path = str(path).replace("\\", "/")
    for pat in SKIP_PATTERNS:
        if pat.search(name_lower) or pat.search(str_path):
            return True

    # Fast content check — only first 500 bytes
    try:
        header = path.read_bytes()[:500].upper()
        for sig in GENERATED_SIGNATURES:
            if sig.upper() in header:
                return True
    except OSError:
        pass

    return False


def filter_files(paths: list[Path]) -> tuple[list[Path], int]:
    """
    Filter out generated files from a list.
    Returns (kept_files, skipped_count).
    """
    kept, skipped = [], 0
    for p in paths:
        if is_generated(p):
            skipped += 1
        else:
            kept.append(p)
    return kept, skipped
